# Generated by Django 4.2.2 on 2023-07-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
