# Generated by Django 4.2.2 on 2023-07-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_liked_by_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
