# Generated by Django 4.2.2 on 2023-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
