# Generated by Django 4.2.2 on 2023-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_body_postcomments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
