# Generated by Django 4.2.2 on 2023-07-16 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_alter_postcomments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='comment_likes',
            field=models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
