# Generated by Django 4.2.7 on 2023-11-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_date_of_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['date_of_event']},
        ),
    ]
