# Generated by Django 4.2.7 on 2023-11-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobs_whatsapp_link'),
        ('chats', '0002_chatgroupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
    ]
