# Generated by Django 4.2.7 on 2023-11-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobs_whatsapp_link'),
        ('chats', '0004_alter_chatgroup_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequestchatroom',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
    ]
